[profile.default]
solc_version = '0.8.22'
# The source directory
src = "contracts"
# The artifact directory
out = 'out'
# A list of paths to look for libraries in
libs = ['lib']
# The test directory
test = 'test'
# Whether to cache builds or not
cache = true
# The cache directory if enabled
cache_path = 'forge-cache'
# Import statement remappings
remappings = [
  'forge-std/=lib/forge-std/src',
  'hyperdrive/=lib/hyperdrive',
  'openzeppelin/=lib/openzeppelin-contracts/contracts',
  'solady/=lib/solady/src',
  'tokenized-strategy/=lib/tokenized-strategy/src',
  'yearn-vaults-v3/=lib/yearn-vaults-v3/contracts',
]
# gas limit - max u64
gas_limit = "18446744073709551615"
# allows the ffi to be used
ffi = true
# strict warnings
# TODO: Reenable
# deny_warnings = true
# optimizer settings
optimizer = true
optimizer_runs = 10000000 # 10 million runs
via_ir = false
# Enable gas-reporting for all contracts
gas_reports = ["*"]
evm_version = "paris"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
