name: Code Coverage

on:
  push:
  pull_request:
  merge_group:

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest-16core
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: false

      - name: forge version
        run: forge --version

      - name: Run coverage
        run: |
          make coverage
          sudo apt-get install lcov
          lcov --remove lcov.info  -o lcov.info 'test/*' 'script/*'

      - name: Edit lcov.info
        run: |
          cat lcov.info | sed '/.*\/test\/.*/,/TN:/d' > tmp.info && mv tmp.info lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: "./lcov.info"
          parallel: true

  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
