name: test

on:
  pull_request:
  merge_group:

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry:
    name: foundry
    strategy:
      fail-fast: true
    env:
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      GNOSIS_CHAIN_RPC_URL: ${{ secrets.GNOSIS_CHAIN_RPC_URL }}
      LINEA_RPC_URL: ${{ secrets.LINEA_RPC_URL }}
      ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
      BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 0.3.0

      - name: Run Forge build
        run: |
          make build
        id: build

      - name: Run Forge tests
        run: |
          make test
        id: test
